databases:
  - name: sickening-hunties
    databaseName: sickening_hunties
    user: elliemarie

services:
  - type: web
    name: sickening-hunties
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sickening-hunties
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false